//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClimaTempoSimples.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrevisaoClima
    {
        public int Id { get; set; }
        public int CidadeId { get; set; }
        public System.DateTime DataPrevisao { get; set; }
        public string Clima { get; set; }
        public Nullable<decimal> TemperaturaMinima { get; set; }
        public Nullable<decimal> TemperaturaMaxima { get; set; }
        public virtual Cidade Cidade { get; set; }
    }
}
